# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [27]:
# Load the dataset
aviation_df = pd.read_csv("data/AviationData.csv", encoding='cp1252', low_memory=False)
state_codes_df = pd.read_csv("data/USState_Codes.csv")


# Display the first few rows of the aviation accident dataset
display(aviation_df.head())

# Basic information about the dataset
print("Dataset Shape:", aviation_df.shape)
print("\nData Types:")
display(aviation_df.dtypes)

# Check for missing values
print("\nMissing Values:")
display(aviation_df.isna().sum().sort_values(ascending=False))

# Summary statistics for numerical columns
print("\nSummary Statistics (Numerical):")
display(aviation_df.describe())

# Summary statistics for all columns (including categorical)
print("\nSummary Statistics (All Columns):")
display(aviation_df.describe(include="all"))
state_codes_df = pd.read_csv("data/USState_Codes.csv")

# Display the first few rows of the aviation accident dataset
display(aviation_df.head())

# Basic information about the dataset
print("Dataset Shape:", aviation_df.shape)
print("\nData Types:")
display(aviation_df.dtypes)

# Check for missing values
print("\nMissing Values:")
display(aviation_df.isna().sum().sort_values(ascending=False))

# Summary statistics for numerical columns
print("\nSummary Statistics (Numerical):")
display(aviation_df.describe())

# Summary statistics for all columns (including categorical)
print("\nSummary Statistics (All Columns):")
display(aviation_df.describe(include="all"))

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

Dataset Shape: (88889, 31)

Data Types:

Event.Id                   object
Investigation.Type         object
Accident.Number            object
Event.Date                 object
Location                   object
Country                    object
Latitude                   object
Longitude                  object
Airport.Code               object
Airport.Name               object
Injury.Severity            object
Aircraft.damage            object
Aircraft.Category          object
Registration.Number        object
Make                       object
Model                      object
Amateur.Built              object
Number.of.Engines         float64
Engine.Type                object
FAR.Description            object
Schedule                   object
Purpose.of.flight          object
Air.carrier                object
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition          object
Broad.phase.of.flight      object
Report.Status              object
Publication.Date           object
dtype: object

Missing Values:

Schedule                  76307
Air.carrier               72241
FAR.Description           56866
Aircraft.Category         56602
Longitude                 54516
Latitude                  54507
Airport.Code              38757
Airport.Name              36185
Broad.phase.of.flight     27165
Publication.Date          13771
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Fatal.Injuries      11401
Engine.Type                7096
Report.Status              6384
Purpose.of.flight          6192
Number.of.Engines          6084
Total.Uninjured            5912
Weather.Condition          4492
Aircraft.damage            3194
Registration.Number        1382
Injury.Severity            1000
Country                     226
Amateur.Built               102
Model                        92
Make                         63
Location                     52
Investigation.Type            0
Event.Date                    0
Accident.Number               0
Event.Id                      0
dtype: int64

Summary Statistics (Numerical):

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

Summary Statistics (All Columns):

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88889,88837,88663,34382,34373,50132,52704,...,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82505,75118
unique,87951,2,88863,14782,27758,219,25589,27154,10374,24870,...,26,13590,NaN,NaN,NaN,NaN,4,12,17074,2924
top,20001212X19172,Accident,CEN22LA149,1984-06-30,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,3,85015,2,25,434,82248,19,24,1488,240,...,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

Dataset Shape: (88889, 31)

Data Types:

Event.Id                   object
Investigation.Type         object
Accident.Number            object
Event.Date                 object
Location                   object
Country                    object
Latitude                   object
Longitude                  object
Airport.Code               object
Airport.Name               object
Injury.Severity            object
Aircraft.damage            object
Aircraft.Category          object
Registration.Number        object
Make                       object
Model                      object
Amateur.Built              object
Number.of.Engines         float64
Engine.Type                object
FAR.Description            object
Schedule                   object
Purpose.of.flight          object
Air.carrier                object
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition          object
Broad.phase.of.flight      object
Report.Status              object
Publication.Date           object
dtype: object

Missing Values:

Schedule                  76307
Air.carrier               72241
FAR.Description           56866
Aircraft.Category         56602
Longitude                 54516
Latitude                  54507
Airport.Code              38757
Airport.Name              36185
Broad.phase.of.flight     27165
Publication.Date          13771
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Fatal.Injuries      11401
Engine.Type                7096
Report.Status              6384
Purpose.of.flight          6192
Number.of.Engines          6084
Total.Uninjured            5912
Weather.Condition          4492
Aircraft.damage            3194
Registration.Number        1382
Injury.Severity            1000
Country                     226
Amateur.Built               102
Model                        92
Make                         63
Location                     52
Investigation.Type            0
Event.Date                    0
Accident.Number               0
Event.Id                      0
dtype: int64

Summary Statistics (Numerical):

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

Summary Statistics (All Columns):

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88889,88837,88663,34382,34373,50132,52704,...,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82505,75118
unique,87951,2,88863,14782,27758,219,25589,27154,10374,24870,...,26,13590,NaN,NaN,NaN,NaN,4,12,17074,2924
top,20001212X19172,Accident,CEN22LA149,1984-06-30,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,3,85015,2,25,434,82248,19,24,1488,240,...,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [28]:
# Inspect columns relevant for filtering
filter_columns = [
    "Event.Date",
    "Aircraft.Category",
    "Amateur.Built",
    "Make",
    "Model"
]

display(aviation_df[filter_columns].head())

# Check for missing values in the relevant columns
print("Missing values:")
display(aviation_df[filter_columns].isna().sum())

# Inspect the unique values that will be used for filtering
for column in filter_columns:
    print(f"\n{column}")
    display(aviation_df[column].value_counts(dropna=False).head(20))


# Reasonable imputations
# Convert Event.Date to datetime
aviation_df["Event.Date"] = pd.to_datetime(
    aviation_df["Event.Date"],
    errors="coerce"
)

# Drop rows missing essential filtering information
aviation_df = aviation_df.dropna(
    subset=["Event.Date", "Aircraft.Category", "Amateur.Built", "Make", "Model"]
)

# Filter the dataset
# Keep accidents from 1983 onwards
aviation_df = aviation_df[
    aviation_df["Event.Date"].dt.year >= 1983
]

# Keep only professionally built aircraft
aviation_df = aviation_df[
    aviation_df["Amateur.Built"] == "No"
]

# Keep only airplanes
aviation_df = aviation_df[
    aviation_df["Aircraft.Category"] == "Airplane"
]

print("Filtered dataset shape:", aviation_df.shape)
display(aviation_df.head())

   Event.Date Aircraft.Category Amateur.Built      Make     Model
0  1948-10-24               NaN            No   Stinson     108-3
1  1962-07-19               NaN            No     Piper  PA24-180
2  1974-08-30               NaN            No    Cessna      172M
3  1977-06-19               NaN            No  Rockwell       112
4  1979-08-02               NaN            No    Cessna       501

Missing values:

Event.Date               0
Aircraft.Category    56602
Amateur.Built          102
Make                    63
Model                   92
dtype: int64

Event.Date

Event.Date
1984-06-30    25
1982-05-16    25
2000-07-08    25
1983-08-05    24
1984-08-25    24
1986-05-17    24
1983-06-05    24
1982-10-03    23
1982-07-09    23
1988-08-07    23
2001-06-16    23
2001-07-21    23
1983-05-28    23
1982-05-01    23
1987-08-23    22
1983-10-01    22
1983-05-30    22
1982-04-25    22
1983-09-10    22
1983-08-06    22
Name: count, dtype: int64

Aircraft.Category

Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

Amateur.Built

Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64

Make

Make
Cessna               22227
Piper                12029
CESSNA                4922
Beech                 4330
PIPER                 2841
Bell                  2134
Boeing                1594
BOEING                1151
Grumman               1094
Mooney                1092
BEECH                 1042
Robinson               946
Bellanca               886
Hughes                 795
Schweizer              629
Air Tractor            595
BELL                   588
Mcdonnell Douglas      526
Aeronca                487
Maule                  445
Name: count, dtype: int64

Model

Model
152          2367
172          1756
172N         1164
PA-28-140     932
150           829
172M          798
172P          689
182           659
180           622
150M          585
PA-18         581
PA-18-150     578
PA-28-180     572
PA-28-161     569
PA-28-181     532
206B          524
737           489
PA-38-112     469
150L          461
G-164A        460
Name: count, dtype: int64

Filtered dataset shape: (21428, 31)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
4149,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,Unknown,NaN,NaN,NaN,NaN,588.0,VMC,Standing,Probable Cause,04-12-2014
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,"Singapore Airlines, Ltd.",NaN,NaN,NaN,588.0,VMC,Taxi,Probable Cause,04-12-2014
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,Skydiving,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016
5957,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,289.0,VMC,Cruise,Probable Cause,01-02-2016

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [29]:
# Clean injury-related columns
injury_columns = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]

# Convert injury columns to numeric
for col in injury_columns:
    aviation_df[col] = pd.to_numeric(aviation_df[col], errors="coerce")

# Assume missing injury counts indicate zero reported injuries
aviation_df[injury_columns] = aviation_df[injury_columns].fillna(0)

# Construct key injury metrics
# Estimate total occupants (crew + passengers)
aviation_df["Total.Occupants"] = (
    aviation_df["Total.Fatal.Injuries"] +
    aviation_df["Total.Serious.Injuries"] +
    aviation_df["Total.Minor.Injuries"] +
    aviation_df["Total.Uninjured"]
)

# Total fatal or serious injuries
aviation_df["Fatal.Serious.Injuries"] = (
    aviation_df["Total.Fatal.Injuries"] +
    aviation_df["Total.Serious.Injuries"]
)

# Proportion of occupants experiencing fatal or serious injuries
aviation_df["Fatal.Serious.Rate"] = (
    aviation_df["Fatal.Serious.Injuries"] /
    aviation_df["Total.Occupants"]
)

# Handle division by zero
aviation_df["Fatal.Serious.Rate"] = (
    aviation_df["Fatal.Serious.Rate"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)
# Inspect the derived metrics
display(
    aviation_df[
        [
            "Total.Occupants",
            "Fatal.Serious.Injuries",
            "Fatal.Serious.Rate"
        ]
    ].head()
)

      Total.Occupants  Fatal.Serious.Injuries  Fatal.Serious.Rate
4149            588.0                     0.0                 0.0
4150            588.0                     0.0                 0.0
4171              2.0                     2.0                 1.0
4285              5.0                     1.0                 0.2
5957            289.0                     0.0                 0.0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [30]:

# Clean Aircraft.damage column
# Inspect existing values
display(aviation_df["Aircraft.damage"].value_counts(dropna=False))

# Standardize text formatting
aviation_df["Aircraft.damage"] = (
    aviation_df["Aircraft.damage"]
    .astype(str)
    .str.strip()
    .str.title()
    )
# Replace missing values with "Unknown"
aviation_df["Aircraft.damage"] = aviation_df["Aircraft.damage"].replace(
    {"Nan": "Unknown"}
)


# Construct destruction metric
# Binary indicator:
# 1 = Aircraft destroyed
# 0 = Aircraft not destroyed
aviation_df["Destroyed"] = (
    aviation_df["Aircraft.damage"] == "Destroyed"
).astype(int)

# Verify the cleaned results
display(aviation_df["Aircraft.damage"].value_counts(dropna=False))
display(aviation_df["Destroyed"].value_counts())

Aircraft.damage
Substantial    16982
Destroyed       2311
NaN             1224
Minor            814
Unknown           97
Name: count, dtype: int64

Aircraft.damage
Substantial    16982
Destroyed       2311
Unknown         1321
Minor            814
Name: count, dtype: int64

Destroyed
0    19117
1     2311
Name: count, dtype: int64

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

### Cleaning the Make Column

The `Make` column identifies the aircraft manufacturer. Before analysis, the following cleaning tasks were performed:

- Standardized manufacturer names by trimming whitespace and applying consistent title-case formatting.

- Replaced placeholder values such as "Unknown" and "Nan" with missing values (NaN).

- Removed records with missing manufacturer names because they cannot be attributed to a specific aircraft make.

- To ensure statistically robust comparisons, only manufacturers with at least 50 accident records were retained for analysis. This reduces the risk of drawing conclusions from very small sample sizes.

In [31]:
# ---------------------------------------
# Investigate and clean the Make column
# ---------------------------------------

# Inspect the most common make values
display(aviation_df["Make"].value_counts(dropna=False).head(30))

# Check missing values
print("Missing Make values:", aviation_df["Make"].isna().sum())

# ---------------------------------------
# Cleaning tasks
# ---------------------------------------
# 1. Convert to string
# 2. Remove leading/trailing whitespace
# 3. Standardize capitalization
# 4. Replace obvious missing placeholders
# 5. Remove rows with missing/unknown make values

aviation_df["Make"] = (
    aviation_df["Make"]
    .astype(str)
    .str.strip()
    .str.title()
)

# Replace common placeholders with NaN
aviation_df["Make"] = aviation_df["Make"].replace({
    "": np.nan,
    "Unknown": np.nan,
    "Nan": np.nan
})

# Drop rows where Make is missing
aviation_df = aviation_df.dropna(subset=["Make"])

# ---------------------------------------
# Keep only makes with a reasonable sample size
# ---------------------------------------

make_counts = aviation_df["Make"].value_counts()

# Threshold for statistical robustness
min_make_count = 50

valid_makes = make_counts[make_counts >= min_make_count].index

aviation_df = aviation_df[
    aviation_df["Make"].isin(valid_makes)
]
# ---------------------------------------
# Verify results
# ---------------------------------------

print(f"Number of makes retained: {len(valid_makes)}")
print(f"Dataset shape after make filtering: {aviation_df.shape}")

display(aviation_df["Make"].value_counts().head(20))

Make
CESSNA                      4864
PIPER                       2802
Cessna                      2278
Piper                       1186
BOEING                      1034
BEECH                       1018
Beech                        413
MOONEY                       238
Boeing                       227
CIRRUS DESIGN CORP           218
AIR TRACTOR INC              217
AIRBUS                       215
BELLANCA                     158
AERONCA                      149
MAULE                        144
Mooney                       125
EMBRAER                      122
Air Tractor                  117
LUSCOMBE                      95
DEHAVILLAND                   91
CHAMPION                      91
STINSON                       91
AIR TRACTOR                   89
CIRRUS                        80
NORTH AMERICAN                79
GRUMMAN                       77
DIAMOND AIRCRAFT IND INC      74
AVIAT AIRCRAFT INC            72
Maule                         71
Grumman                       70
Name: count, dtype: int64

Missing Make values: 0
Number of makes retained: 36
Dataset shape after make filtering: (17879, 35)

Make
Cessna                7142
Piper                 3988
Beech                 1431
Boeing                1261
Mooney                 363
Airbus                 243
Cirrus Design Corp     220
Bellanca               219
Air Tractor Inc        219
Maule                  215
Air Tractor            206
Aeronca                200
Champion               158
Embraer                152
Grumman                147
Luscombe               141
Cirrus                 137
Stinson                129
Mcdonnell Douglas      108
North American         106
Name: count, dtype: int64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [32]:
# Clean the Model column

# Remove rows with missing model information
aviation_df = aviation_df.dropna(subset=["Model"])

# Standardize model names
aviation_df["Model"] = (
    aviation_df["Model"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Inspect the most common models
display(aviation_df["Model"].value_counts().head(20))


# Check whether model names are unique to a make
# Count the number of makes associated with each model
model_make_counts = (
    aviation_df.groupby("Model")["Make"]
    .nunique()
    .sort_values(ascending=False)
)

print("Models associated with more than one make:")
display(model_make_counts[model_make_counts > 1].head(20))


# Create a unique aircraft identifier

aviation_df["Aircraft.Type"] = (
    aviation_df["Make"] + " " + aviation_df["Model"]
)

# Inspect the new identifier
display(
    aviation_df[
        ["Make", "Model", "Aircraft.Type"]
    ].head()
)

Model
172          769
737          403
152          316
182          304
172S         276
PA28         273
172N         249
SR22         240
180          213
A36          181
172M         180
150          179
PA-18-150    175
PA-28-140    169
172P         143
140          117
172R         109
170B         107
PA-28-180    105
PA-28-161    102
Name: count, dtype: int64

Models associated with more than one make:

Model
S2R        3
7AC        3
500        3
8KCAB      3
8GCBC      3
400        3
7GCBC      3
7GCAA      3
7EC        3
7ECA       3
AT-402A    2
AT-402     2
B300       2
AT 502     2
200        2
B200       2
AT-802A    2
AT-802     2
AT-602     2
AT 602     2
Name: Make, dtype: int64

              Make      Model       Aircraft.Type
4150        Boeing        747          Boeing 747
4171         Piper  PA-28-140     Piper PA-28-140
4285  De Havilland      DHC-6  De Havilland DHC-6
6760        Boeing    727-200      Boeing 727-200
6806         Beech        C35           Beech C35

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [33]:
# Clean additional analysis columns
columns_to_clean = [
    "Engine.Type",
    "Weather.Condition",
    "Number.of.Engines",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

# Inspect each column before cleaning
for col in columns_to_clean:
    print(f"\n{'='*60}")
    print(f"{col}")
    display(aviation_df[col].value_counts(dropna=False))


# Standardize text columns
text_columns = [
    "Engine.Type",
    "Weather.Condition",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

for col in text_columns:
    aviation_df[col] = (
        aviation_df[col]
        .astype("string")
        .str.strip()
        .str.title()
    )

# Standardize Number.of.Engines
aviation_df["Number.of.Engines"] = pd.to_numeric(
    aviation_df["Number.of.Engines"],
    errors="coerce"
)# Inspect cleaned columns
print("\nCleaned columns:")
for col in columns_to_clean:
    print(f"\n{'='*60}")
    print(f"{col}")
    display(aviation_df[col].value_counts(dropna=False))

============================================================
Engine.Type

Engine.Type
Reciprocating      12835
NaN                 3214
Turbo Prop           931
Turbo Fan            701
Unknown              105
Turbo Jet             71
Geared Turbofan       12
Turbo Shaft            9
UNK                    1
Name: count, dtype: int64

============================================================
Weather.Condition

Weather.Condition
VMC    14295
NaN     2417
IMC      905
Unk      186
UNK       76
Name: count, dtype: int64

============================================================
Number.of.Engines

Number.of.Engines
1.0    13222
2.0     2470
NaN     2089
4.0       67
3.0       26
0.0        5
Name: count, dtype: int64

============================================================
Purpose.of.flight

Purpose.of.flight
Personal                     9844
NaN                          3047
Instructional                2410
Aerial Application            724
Business                      409
Unknown                       303
Positioning                   269
Skydiving                     157
Aerial Observation            147
Other Work Use                121
Banner Tow                     86
Flight Test                    73
Ferry                          72
Executive/corporate            65
Glider Tow                     29
Public Aircraft - Federal      28
Public Aircraft                27
Public Aircraft - State        21
Air Race show                  15
Firefighting                   12
Public Aircraft - Local        11
PUBS                            3
Air Race/show                   2
Air Drop                        2
ASHO                            2
Name: count, dtype: int64

============================================================
Broad.phase.of.flight

Broad.phase.of.flight
NaN            15427
Landing         1110
Takeoff          425
Cruise           238
Approach         210
Maneuvering      127
Taxi              99
Go-around         81
Descent           62
Climb             52
Standing          35
Unknown           11
Other              2
Name: count, dtype: int64

Cleaned columns:

============================================================
Engine.Type

Engine.Type
Reciprocating      12835
<NA>                3214
Turbo Prop           931
Turbo Fan            701
Unknown              105
Turbo Jet             71
Geared Turbofan       12
Turbo Shaft            9
Unk                    1
Name: count, dtype: Int64

============================================================
Weather.Condition

Weather.Condition
Vmc     14295
<NA>     2417
Imc       905
Unk       262
Name: count, dtype: Int64

============================================================
Number.of.Engines

Number.of.Engines
1.0    13222
2.0     2470
NaN     2089
4.0       67
3.0       26
0.0        5
Name: count, dtype: int64

============================================================
Purpose.of.flight

Purpose.of.flight
Personal                     9844
<NA>                         3047
Instructional                2410
Aerial Application            724
Business                      409
Unknown                       303
Positioning                   269
Skydiving                     157
Aerial Observation            147
Other Work Use                121
Banner Tow                     86
Flight Test                    73
Ferry                          72
Executive/Corporate            65
Glider Tow                     29
Public Aircraft - Federal      28
Public Aircraft                27
Public Aircraft - State        21
Air Race Show                  15
Firefighting                   12
Public Aircraft - Local        11
Pubs                            3
Air Race/Show                   2
Air Drop                        2
Asho                            2
Name: count, dtype: Int64

============================================================
Broad.phase.of.flight

Broad.phase.of.flight
<NA>           15427
Landing         1110
Takeoff          425
Cruise           238
Approach         210
Maneuvering      127
Taxi              99
Go-Around         81
Descent           62
Climb             52
Standing          35
Unknown           11
Other              2
Name: count, dtype: Int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [34]:
# Remove columns with excessive missing values
# Calculate the percentage of missing values for each column
missing_percent = aviation_df.isna().mean() * 100

# Display missing value percentages
missing_summary = (
    missing_percent
    .sort_values(ascending=False)
    .to_frame(name="Missing (%)")
)

display(missing_summary)

# Identify columns with more than 50% missing values
columns_to_drop = missing_percent[missing_percent > 50].index.tolist()
print("Columns to be dropped (>50% missing values):")
print(columns_to_drop)

# Drop the identified columns
aviation_df = aviation_df.drop(columns=columns_to_drop)

# Confirm the remaining dataframe shape
print(f"\nUpdated dataframe shape: {aviation_df.shape}")

# Display remaining columns
display(aviation_df.head())

                        Missing (%)
Schedule                  88.036244
Broad.phase.of.flight     86.285586
Air.carrier               52.749035
Airport.Code              34.850942
Airport.Name              34.258068
Report.Status             21.170088
Engine.Type               17.976397
Purpose.of.flight         17.042340
Weather.Condition         13.518653
Number.of.Engines         11.684099
Longitude                 10.632586
Latitude                  10.615806
Publication.Date           4.407405
Injury.Severity            4.010291
FAR.Description            1.924045
Registration.Number        0.917277
Location                   0.022373
Country                    0.005593
Total.Occupants            0.000000
Total.Minor.Injuries       0.000000
Fatal.Serious.Injuries     0.000000
Fatal.Serious.Rate         0.000000
Destroyed                  0.000000
Total.Uninjured            0.000000
Event.Id                   0.000000
Total.Serious.Injuries     0.000000
Total.Fatal.Injuries       0.000000
Investigation.Type         0.000000
Amateur.Built              0.000000
Model                      0.000000
Make                       0.000000
Aircraft.Category          0.000000
Aircraft.damage            0.000000
Event.Date                 0.000000
Accident.Number            0.000000
Aircraft.Type              0.000000

Columns to be dropped (>50% missing values):
['Schedule', 'Air.carrier', 'Broad.phase.of.flight']

Updated dataframe shape: (17879, 33)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,Total.Occupants,Fatal.Serious.Injuries,Fatal.Serious.Rate,Destroyed,Aircraft.Type
4150,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,0.0,588.0,Vmc,Probable Cause,04-12-2014,588.0,0.0,0.0,0,Boeing 747
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,0.0,0.0,Imc,Probable Cause,02-05-2011,2.0,2.0,1.0,1,Piper PA-28-140
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,0.0,4.0,Vmc,Probable Cause,17-10-2016,5.0,1.0,0.2,0,De Havilland DHC-6
6760,20001214X45013,Incident,CHI84IA041,1983-11-08,"CHICAGO, IL",United States,NaN,NaN,ORD,O'HARE,...,0.0,100.0,Vmc,Probable Cause,11-06-2018,100.0,0.0,0.0,0,Boeing 727-200
6806,20001214X45188,Accident,NYC84LA028,1983-11-13,"MARTHA'S VINEYARD, MA",United States,NaN,NaN,NaN,NaN,...,0.0,1.0,Vmc,Probable Cause,05-05-2011,1.0,0.0,0.0,0,Beech C35

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [35]:

# Save cleaned dataset
output_path = "data/AviationData_Clean.csv"

aviation_df.to_csv(output_path, index=False)

print(f"Cleaned dataset successfully saved to: {output_path}")
print(f"Final dataset shape: {aviation_df.shape}")

Cleaned dataset successfully saved to: data/AviationData_Clean.csv
Final dataset shape: (17879, 33)